name: Build and Test with Gradle

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'  # Adjust to your Gradle version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest

      - name: Upload PMD Report
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: build/reports/pmd

      - name: Check PMD Report
        run: |
          if find build/reports/pmd -name '*.xml' -exec grep -q 'violations' {} \; then
            echo "PMD found issues"
            exit 1
          else
            echo "No PMD issues found"
          fi
