name: Java CI with Gradle and PMD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and PMD Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '7.6' # Specify the Gradle version you are using

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run PMD Analysis
        run: ./gradlew pmdMain
