name: Java CI with Gradle and Spot Bug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Spot Bug Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '7.6'

      - name: Run Spot Bug Analysis
        run: ./gradlew spotbugsMain

      - name: Upload SpotBugs reports
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-reports
          path: test-code-quality-tools-api/build/reports/spotbugs

      - name: Check Spot Bug Report for Issues
        id: check_spotbug
        run: |
          if grep -q "<BugInstance" test-code-quality-tools-api/build/reports/spotbugs/spotbugs.xml; then
            echo "SpotBug found issues in main source code."
            exit 1
          fi
        continue-on-error: false
