name: Run Integration Tests

on:
  pull_request:
    branches:
      - '*'
      - '!main'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 19
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
      - name: Run Integration Test Suite
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
        run: |
          ./gradlew integrationTest
