name: 'Spotless Check'

on:
  pull_request:
    branches:
      - '*'

jobs:
  spotless:
    name: 'Run spotless check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b
        with:
          distribution: 'corretto'
          java-version: 19
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
      - name: Run spotless check
        run: ./gradlew spotlessCheck
      - name: Cleanup Gradle Cache
        uses: ./.github/actions/gradle-cleanup