name: subgraph-publish-dev

on:
  push:
    branches:
      - '!main'
      - 'develop'
      
jobs:
  schema-check:
    uses: triplelift-internal/shared-gha/.github/workflows/subgraph-publish.yml@main
    # remove this condition to enable the workflow
    if: false
    with:
      application: test-code-quality-tools-api
      environment: dev
      routing_url: https://test-code-quality-tools-api.dev.triplelift.net/graphql
    secrets:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF:  ${{ secrets.APOLLO_GRAPH_REF_DEV }}
      GITHUB_SHA: ${{ github.event.pull_request.head.sha }}